database_name: Car_Insurance_claim_1303_v1
ds_environment: dev
sdk_session_id_dev: 6d20dcace8ab49f7a6178e91836ffcb9
sdk_session_id_uat: 64f8333b22dcbfd20b053385
sdk_session_id_prod: 64ec92d6117247877965d152
data_engineering:
  data_engineering_ft:
    features_dbfs_path: dbfs:/FileStore/Car_Insurance_X.csv
    features_table_name: features_table_Claim_1303_v1
    primary_keys:
    - Index
  data_engineering_gt:
    ground_truth_dbfs_path: dbfs:/FileStore/Car_Insurance_Y.csv
    ground_truth_table_name:  groundtruth_table_11303_v1
    primary_keys:
    - Index
data_prep_deployments:
  data_prep_deployment_ft:
    batch_size: 50
    cron_job_schedule: 0 */5 * ? * *
    features_dbfs_path: features_table_1303_v1
    is_scheduled: true
    primary_keys:
    - Index
    transformed_features_table_name: DPD_features_1103_v22
  data_prep_deployment_gt:
    batch_size: 50
    cron_job_schedule: 0 */5 * ? * *
    ground_truth_dbfs_path: groundtruth_table_1303_v1
    is_scheduled: true
    primary_keys:
    - Index
    transformed_ground_truth_table_name: DPD_groundtruth_1103_v22
feature_pipelines:
  feature_pipelines_ft:
    features_dbfs_path: features_table_1303_v1
    is_scheduled: false
    primary_keys:
    - Index
    transformed_features_table_name: Transformed_features_1303_v1
  feature_pipelines_gt:
    ground_truth_dbfs_path: groundtruth_table_1303_v1
    is_scheduled: false
    primary_keys:
    - Index
    transformed_ground_truth_table_name: Transformed_groundtruth_1303_v1
inference:
  batch_size: 50
  cron_job_schedule: 0 */5 * ? * *
  ground_truth_path: DPD_groundtruth_1103_v22
  model_name: model_1303_v1
  model_version: '1'
  output_table_name: inference_output_1103_v22
  transformed_features_path: DPD_features_1103_v22
train:
  feature_columns:
  - Education
  - Marital_Status
  - Income
  - Kidhome
  - Teenhome
  - Recency
  - MntWines
  - MntFruits
  - MntMeatProducts
  - MntFishProducts
  - MntSweetProducts
  - MntGoldProds
  - NumDealsPurchases
  - NumWebPurchases
  - NumCatalogPurchases
  - NumStorePurchases
  - NumWebVisitsMonth
  - Complain
  - Age
  - Reg_year
  - Reg_month
  - Reg_week
  feature_table_path: Transformed_features_1303_v1
  ground_truth_path: Transformed_groundtruth_1303_v1
  model_name: model_1303_v1
  model_version: '1'
  primary_keys:
  - Index
  target_columns:
  - Response
  test_size: 0.2
  train_output_table_name: train_output_1303_v1
  hyperparameter_tuning:
    max_evaluations : 20
    primary_metric : accuracy
    search_range :
      solver : 
        - lbfgs
        - liblinear
      fit_intercept : 
        - true
        - false
    max_evaluations : 20
    stop_early : false
    run_parallel : false
