database_name: Car_Insurance_claim_1403
ds_environment: dev
sdk_session_id_dev: 1c89ba4da6964271aa33cb33f9fab0b6
sdk_session_id_uat: ef0207d9482d43e191e57fe4758db6f3
# sdk_session_id_prod: 64ec92d6117247877965d152
data_engineering:
  data_engineering_ft:
    features_dbfs_path: dbfs:/FileStore/Car_Insurance_X.csv
    features_table_name: features_table_Claim_1403_v0
    primary_keys:
    - Index
  data_engineering_gt:
    ground_truth_dbfs_path: dbfs:/FileStore/Car_Insurance_Y.csv
    ground_truth_table_name:  groundtruth_table_1403_v0
    primary_keys:
    - Index
data_prep_deployments:
  data_prep_deployment_ft:
    batch_size: 1000
    cron_job_schedule: 0 */5 * ? * *
    features_dbfs_path: features_table_Claim_1403_v0
    is_scheduled: true
    primary_keys:
    - Index
    transformed_features_table_name: DPD_features_Claim_1403_v0
  data_prep_deployment_gt:
    batch_size: 1000
    cron_job_schedule: 0 */5 * ? * *
    ground_truth_dbfs_path: groundtruth_table_1403_v0
    is_scheduled: true
    primary_keys:
    - Index
    transformed_ground_truth_table_name: DPD_groundtruth_Claim_1403_v0
feature_pipelines:
  feature_pipelines_ft:
    features_dbfs_path: features_table_Claim_1403_v0
    is_scheduled: false
    primary_keys:
    - Index
    transformed_features_table_name: Transformed_features_1403_v0
  feature_pipelines_gt:
    ground_truth_dbfs_path: groundtruth_table_1403_v0
    is_scheduled: false
    primary_keys:
    - Index
    transformed_ground_truth_table_name: Transformed_groundtruth_1403_v0
inference:
  batch_size: 1000
  cron_job_schedule: 0 */5 * ? * *
  ground_truth_path: DPD_groundtruth_Claim_1403_v0
  model_name: model_1303_v1
  model_version: '1'
  output_table_name: inference_output_Claim_1403_v0
  transformed_features_path: DPD_features_Claim_1403_v0
train:
  feature_columns:
  - AGE 
  - GENDER 
  - RACE 
  - DRIVING_EXPERIENCE 
  - EDUCATION
  - INCOME 
  - CREDIT_SCORE 
  - VEHICLE_OWNERSHIP 
  - VEHICLE_YEAR
  - MARRIED 
  - CHILDREN 
  - ANNUAL_MILEAGE 
  - VEHICLE_TYPE
  - SPEEDING_VIOLATIONS 
  - DUIS 
  - PAST_ACCIDENTS
  feature_table_path: Transformed_features_1403_v0
  ground_truth_path: Transformed_groundtruth_1403_v0
  model_name: model_1303_v1
  model_version: '1'
  primary_keys:
  - Index
  target_columns:
  - OUTCOME
  test_size: 0.2
  train_output_table_name: train_output_1403_v0
  hyperparameter_tuning:
    max_evaluations : 20
    primary_metric : accuracy
    search_range :
      solver : 
        - lbfgs
        - liblinear
      fit_intercept : 
        - true
        - false
    max_evaluations : 20
    stop_early : false
    run_parallel : false
